name = "Metal"
uuid = "dde4c033-4e86-420c-a63e-0dd931031962"
authors = ["Filippo Vicentini <filippovicentini@gmail.com>",
           "Tim Besard <tim.besard@gmail.com>",
           "Max Hawkins <max.hawkins65@gmail.com>"]
version = "0.1.2"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
GPUCompiler = "61eb1bfa-7361-4325-ad38-22787b887f55"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Metal_LLVM_Tools_jll = "0418c028-ff8c-56b8-a53e-0f9676ed36fc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
cmt_jll = "65323cdd-17ec-5719-9643-72016a7f97e3"

[compat]
Adapt = "3"
CEnum = "0.4"
ExprTools = "0.1"
GPUArrays = "8.4"
GPUCompiler = "0.18"
Reexport = "1.0"
LLVM = "4.15"
Metal_LLVM_Tools_jll = "~0.3"
cmt_jll = "~0.1"
julia = "1.8"
