[deps]
CMake_jll = "3f4e10e2-61f2-5801-8945-23b9d642d0e6"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
Git_jll = "f8c6e375-362e-5223-8a59-34ff63f689eb"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Ninja_jll = "76642167-d241-5cee-8c94-7a494e8cb7b7"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"

[compat]
Git_jll = "< 2.36"
